import type { NextPage } from 'next'
// import Header from 'component/header'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Header: NextPage = () => {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Header
